#!/usr/bin/env python3
"""Reproducible nondegeneracy validation for the one-dimensional cold-port adjoint.

The cold-port adjoint used in the reported calculations obeys, in the normalized leg
coordinate ``u=x/L``,

    psi_uu + c1(u) psi_u + c0(u) psi = 0,
    psi(0)=1, psi(1)=0,

where

    c1 = I_i tau L/(kappa A),
    c0 = rho_T I_i**2 L**2/(kappa A**2).

For the associated homogeneous Dirichlet problem define

    P(u)=exp(integral_0^u c1(s) ds).

Multiplication by ``P`` gives the self-adjoint form

    (P psi_u)_u + P c0 psi = 0.

The Poincare inequality proves a sufficient uniqueness condition

    eta = (Pmax/Pmin) * ||max(c0,0)||_infinity / pi**2 < 1.

Unlike a bound involving ``rho_T`` alone, ``eta`` retains the integrating
factor generated by the first-order Thomson term.  A sharper second condition
uses the Liouville substitution ``psi=exp[-A/2]z``, ``A'=c1``:

    z_uu + V z = 0,   V=c0-c1_u/2-c1**2/4.

Thus ``sup(max(V,0))/pi**2 < 1`` is also sufficient.  The script evaluates
both conditions and an independent shooting determinant on every one-dimensional
baseline used by the PbSe and BTS/BST material-system analyses, including the
published-property perturbation families and the finite-difference baselines.
The calculation is a mathematical well-posedness validation, not experimental
validation.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
import hashlib
import json
import math
from pathlib import Path
import platform
import sys
from typing import Any, Iterable

import numpy as np
from numpy.typing import NDArray
from scipy.integrate import cumulative_trapezoid, solve_ivp
from scipy.interpolate import PchipInterpolator


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.analysis import analyze_bts_bst_endpoint_zero_common_mode as bts  # noqa: E402
from scripts.analysis import analyze_pbse_common_mode_contribution as pb_common  # noqa: E402
from scripts.analysis import analyze_pbse_device_forward_constraint as pb_forward  # noqa: E402
from scripts.analysis import analyze_pbse_gamma_identifiability as pb_ident  # noqa: E402
from scripts.analysis.analyze_common_mode_transfer_kernel import (  # noqa: E402
    build_empirical_perturbed_couple,
)
from scripts.tec_1d_solver import (  # noqa: E402
    PchipTemperatureProperty,
    TemperatureDependentLeg,
    TemperatureDependentNumericalCouple,
    solve_temperature_dependent_couple,
)


FloatArray = NDArray[np.float64]

SCHEMA_VERSION = "adjoint_nondegeneracy/v1"
ANALYSIS_ID = "ADJOINT-NONDEGENERACY-20260826"
DEFAULT_JSON = ROOT / "results/scientific_analysis/adjoint_nondegeneracy.json"
DEFAULT_CSV = ROOT / "results/scientific_analysis/adjoint_nondegeneracy.csv"
PB_IDENT_JSON = ROOT / "results/scientific_analysis/pbse_gamma_identifiability_results.json"
PB_COMMON_JSON = ROOT / "results/scientific_analysis/pbse_common_mode_contribution_results.json"
BTS_JSON = ROOT / "results/scientific_analysis/bts_bst_endpoint_zero_common_mode_results.json"


class ValidationError(RuntimeError):
    """Raised when a well-posedness acceptance criterion is not met."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValidationError(message)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def locator(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path.resolve())


@dataclass(frozen=True)
class Case:
    material_family: str
    scenario_family: str
    scenario_id: str
    variant: str
    current_a: float
    couple: TemperatureDependentNumericalCouple


def _solve(couple: TemperatureDependentNumericalCouple, current_a: float):
    return solve_temperature_dependent_couple(
        couple,
        float(current_a),
        initial_mesh_points=41,
        output_points=501,
        relative_tolerance=3.0e-9,
        max_nodes=16000,
    )


def _diagnose_leg(
    leg: TemperatureDependentLeg,
    solution: Any,
    *,
    case: Case,
    leg_name: str,
) -> dict[str, Any]:
    coordinate = np.asarray(solution.coordinate_m, dtype=float)
    u = coordinate / leg.length_m
    temperature = np.asarray(solution.temperature_k, dtype=float)
    current = float(solution.signed_current_a)
    kappa = np.asarray(leg.thermal_conductivity.evaluate(temperature), dtype=float)
    tau = temperature * np.asarray(leg.seebeck.derivative(temperature), dtype=float)
    rho_t = np.asarray(leg.electrical_resistivity.derivative(temperature), dtype=float)
    c1 = current * tau * leg.length_m / (kappa * leg.area_m2)
    c0 = (
        rho_t
        * current**2
        * leg.length_m**2
        / (kappa * leg.area_m2**2)
    )
    require(bool(np.all(np.isfinite(c1))), "non-finite c1 coefficient")
    require(bool(np.all(np.isfinite(c0))), "non-finite c0 coefficient")

    log_weight = np.concatenate(([0.0], cumulative_trapezoid(c1, u)))
    log_weight -= float(np.min(log_weight))
    weight = np.exp(log_weight)
    weight_ratio = float(np.max(weight) / np.min(weight))
    positive_c0_sup = float(max(0.0, np.max(c0)))
    eta = weight_ratio * positive_c0_sup / math.pi**2

    c1_derivative = np.asarray(
        PchipInterpolator(u, c1, extrapolate=False).derivative()(u), dtype=float
    )
    liouville_potential = c0 - 0.5 * c1_derivative - 0.25 * c1**2
    positive_liouville_sup = float(max(0.0, np.max(liouville_potential)))
    liouville_eta = positive_liouville_sup / math.pi**2

    c1_law = PchipInterpolator(u, c1, extrapolate=False)
    c0_law = PchipInterpolator(u, c0, extrapolate=False)

    def ode(value_u: float, state: FloatArray) -> FloatArray:
        return np.asarray(
            [
                state[1],
                -float(c1_law(value_u)) * state[1]
                - float(c0_law(value_u)) * state[0],
            ],
            dtype=float,
        )

    fundamental = solve_ivp(
        ode,
        (0.0, 1.0),
        np.asarray([0.0, 1.0]),
        method="DOP853",
        rtol=2.0e-11,
        atol=2.0e-13,
        max_step=0.005,
    )
    require(fundamental.success, f"shooting IVP failed: {fundamental.message}")
    determinant = float(fundamental.y[0, -1])

    return {
        "material_family": case.material_family,
        "scenario_family": case.scenario_family,
        "scenario_id": case.scenario_id,
        "variant": case.variant,
        "current_a": float(case.current_a),
        "leg": leg_name,
        "signed_branch_current_a": current,
        "temperature_minimum_k": float(np.min(temperature)),
        "temperature_maximum_k": float(np.max(temperature)),
        "c1_minimum": float(np.min(c1)),
        "c1_maximum": float(np.max(c1)),
        "c0_minimum": float(np.min(c0)),
        "c0_maximum": float(np.max(c0)),
        "integrating_factor_ratio": weight_ratio,
        "positive_c0_supremum": positive_c0_sup,
        "poincare_eta": float(eta),
        "coercivity_margin_lower_bound": float(1.0 - eta),
        "liouville_potential_minimum": float(np.min(liouville_potential)),
        "liouville_potential_maximum": float(np.max(liouville_potential)),
        "liouville_poincare_eta": float(liouville_eta),
        "liouville_coercivity_margin_lower_bound": float(1.0 - liouville_eta),
        "at_least_one_analytic_sufficient_condition_passes": bool(
            eta < 1.0 or liouville_eta < 1.0
        ),
        "homogeneous_shooting_determinant": determinant,
        "homogeneous_shooting_determinant_absolute": abs(determinant),
        "baseline_energy_residual_fraction": float(
            solution.relative_local_energy_residual
        ),
    }


def _flatten(couple: TemperatureDependentNumericalCouple):
    cold = couple.cold_temperature_k
    common_at_cold = 0.5 * float(
        couple.p_leg.seebeck.evaluate([cold])[0]
        + couple.n_leg.seebeck.evaluate([cold])[0]
    )
    return pb_common.build_flattened_common_mode_couple(couple, common_at_cold)


def _with_seebeck(
    base: TemperatureDependentNumericalCouple,
    p_property: Any,
    n_property: Any,
) -> TemperatureDependentNumericalCouple:
    return pb_ident._build_couple_with_properties(base, p_property, n_property)


def _pbse_affine_from_record(
    base: TemperatureDependentNumericalCouple,
    record: dict[str, Any],
    center_k: float,
    half_range_k: float,
) -> TemperatureDependentNumericalCouple:
    perturbation = record.get("perturbation", {})
    scenario = str(record["scenario_id"])

    def property_for(carrier: str):
        source = base.p_leg.seebeck if carrier == "p" else base.n_leg.seebeck
        kwargs = {
            "normalization_center_k": center_k,
            "normalization_half_range_k": half_range_k,
            "gain_constant_fraction": 0.0,
            "gain_drift_fraction": 0.0,
            "additive_constant_v_per_k": 0.0,
            "additive_drift_v_per_k": 0.0,
        }
        if scenario.startswith("common_constant_offset_"):
            kwargs["additive_constant_v_per_k"] = perturbation["common_offset_v_per_k"]
        elif scenario.startswith("leg_constant_offsets_"):
            kwargs["additive_constant_v_per_k"] = perturbation[f"{carrier}_offset_v_per_k"]
        elif scenario.startswith("leg_gains_"):
            kwargs["gain_constant_fraction"] = perturbation[f"{carrier}_gain_fraction"]
        elif scenario.startswith("multiplicative_temperature_drifts_"):
            kwargs["gain_drift_fraction"] = perturbation[
                f"{carrier}_endpoint_gain_amplitude_fraction"
            ]
        elif scenario.startswith("common_additive_temperature_drift_"):
            kwargs["additive_drift_v_per_k"] = perturbation[
                "endpoint_additive_amplitude_v_per_k"
            ]
        elif scenario.startswith("differential_additive_temperature_drift_"):
            kwargs["additive_drift_v_per_k"] = perturbation[
                f"{carrier}_endpoint_additive_amplitude_v_per_k"
            ]
        elif scenario.startswith("common_additive_drift_sweep_"):
            kwargs["additive_drift_v_per_k"] = perturbation[
                "endpoint_additive_amplitude_v_per_k"
            ]
        else:
            raise ValidationError(f"unsupported affine scenario: {scenario}")
        return pb_ident.AffinePerturbedSeebeckProperty(source, **kwargs)

    return _with_seebeck(base, property_for("p"), property_for("n"))


def _pbse_corner_from_record(
    base: TemperatureDependentNumericalCouple,
    inputs: dict[str, Any],
    record: dict[str, Any],
) -> TemperatureDependentNumericalCouple:
    properties = []
    for carrier in ("p", "n"):
        temperature, values = pb_forward._fig1_arrays(inputs[f"{carrier}_seebeck"])
        signs = record["perturbation"][f"{carrier}_first_four_signs"]
        modified = np.asarray(values, dtype=float).copy()
        modified[:4] *= 1.0 + pb_ident.SEEBECK_RELATIVE_METHOD_CEILING * np.asarray(
            signs, dtype=float
        )
        properties.append(PchipTemperatureProperty(temperature, modified))
    return _with_seebeck(base, properties[0], properties[1])


def _pbse_representation_cases(
    base: TemperatureDependentNumericalCouple,
    inputs: dict[str, Any],
) -> list[tuple[str, TemperatureDependentNumericalCouple]]:
    output: list[tuple[str, TemperatureDependentNumericalCouple]] = []
    p_t, p_s = pb_forward._fig1_arrays(inputs["p_seebeck"])
    n_t, n_s = pb_forward._fig1_arrays(inputs["n_seebeck"])
    for interpolation in ("piecewise_linear", "bound_checked_smooth_quadratic"):
        output.append(
            (
                interpolation,
                _with_seebeck(
                    base,
                    pb_ident._source_property(interpolation, p_t, p_s),
                    pb_ident._source_property(interpolation, n_t, n_s),
                ),
            )
        )
    vector = json.loads(pb_ident.VECTOR_CANDIDATE.read_text(encoding="utf-8"))
    vector_arrays = pb_ident._vector_b_seebeck_arrays(vector, inputs)
    output.append(
        (
            "independent_vector_extractor_B",
            _with_seebeck(
                base,
                PchipTemperatureProperty(*vector_arrays["p"]),
                PchipTemperatureProperty(*vector_arrays["n"]),
            ),
        )
    )
    return output


def _case_pair(
    material: str,
    family: str,
    scenario: str,
    couple: TemperatureDependentNumericalCouple,
    current: float,
    *,
    include_flattened: bool = True,
) -> list[Case]:
    output = [Case(material, family, scenario, "original", float(current), couple)]
    if include_flattened:
        output.append(
            Case(material, family, scenario, "alpha_preserving_flattened", float(current), _flatten(couple))
        )
    return output


def build_pbse_cases() -> list[Case]:
    inputs = pb_forward.load_inputs()
    target = inputs["target"]
    hot = float(target["hot_side_temperature_k"])
    cold = hot - float(target["delta_t_max_k"])
    base = pb_forward.build_couple(inputs, pb_forward.SCENARIOS["nominal"], cold, hot)
    ident_result = json.loads(PB_IDENT_JSON.read_text(encoding="utf-8"))
    common_result = json.loads(PB_COMMON_JSON.read_text(encoding="utf-8"))
    nominal_current = float(
        ident_result["target_condition"]["nominal_optimum_current_a"]
    )
    p_t, _ = pb_forward._fig1_arrays(inputs["p_seebeck"])
    n_t, _ = pb_forward._fig1_arrays(inputs["n_seebeck"])
    center, half_range = pb_ident._full_support_normalization(p_t, n_t)

    cases: list[Case] = []
    cases.extend(
        _case_pair(
            "PbSe/Cr",
            "primary_reference_state",
            "nominal_transport",
            base,
            nominal_current,
        )
    )
    # Complete signed current sweep used for the PbSe mechanism plot.
    for record in common_result["signed_current_sweep"]:
        cases.extend(
            _case_pair(
                "PbSe/Cr",
                "signed_current_sweep",
                "nominal_transport",
                base,
                float(record["current_a"]),
            )
        )

    scenario_records: list[dict[str, Any]] = list(
        ident_result["structured_Seebeck_scenarios"]
    )
    scenario_records.extend(ident_result["alpha_preserving_common_drift_sweep"]["sweep"])
    seen: set[str] = set()
    for record in scenario_records:
        scenario_id = str(record["scenario_id"])
        if scenario_id in seen:
            continue
        seen.add(scenario_id)
        couple = _pbse_affine_from_record(base, record, center, half_range)
        currents = {
            nominal_current,
            float(record["reoptimized"]["original_optimum_current_a"]),
            float(record["reoptimized"]["flattened_optimum_current_a"]),
        }
        for current in sorted(currents):
            cases.extend(
                _case_pair(
                    "PbSe/Cr",
                    str(record["family"]),
                    scenario_id,
                    couple,
                    current,
                )
            )

    for record in ident_result["monotone_pointwise_corner_screen"]["records"]:
        couple = _pbse_corner_from_record(base, inputs, record)
        currents = {
            nominal_current,
            float(record["reoptimized"]["original_optimum_current_a"]),
            float(record["reoptimized"]["flattened_optimum_current_a"]),
        }
        for current in sorted(currents):
            cases.extend(
                _case_pair(
                    "PbSe/Cr",
                    "monotone_pointwise_corners",
                    str(record["scenario_id"]),
                    couple,
                    current,
                )
            )

    for record in ident_result["branch_transfer_condition_sensitivity"]["records"]:
        p = record["perturbation"]
        couple = pb_ident._build_transport_scaled_couple(
            base,
            p_sigma_scale=float(p["p_sigma_scale"]),
            n_sigma_scale=float(p["n_sigma_scale"]),
            p_kappa_scale=float(p["p_kappa_scale"]),
            n_kappa_scale=float(p["n_kappa_scale"]),
        )
        currents = {
            nominal_current,
            float(record["reoptimized"]["original_optimum_current_a"]),
            float(record["reoptimized"]["flattened_optimum_current_a"]),
        }
        for current in sorted(currents):
            cases.extend(
                _case_pair(
                    "PbSe/Cr",
                    "sigma_kappa_corners",
                    str(record["scenario_id"]),
                    couple,
                    current,
                )
            )

    representation_records = {
        str(record["scenario_id"]): record
        for record in ident_result["interpolation_and_digitization"]["records"]
    }
    route_record = ident_result["interpolation_and_digitization"]["digitization_only"][
        "route_B_effect_record"
    ]
    representation_records[str(route_record["scenario_id"])] = route_record
    for scenario_id, couple in _pbse_representation_cases(base, inputs):
        record = representation_records[scenario_id]
        currents = {
            nominal_current,
            float(record["reoptimized"]["original_optimum_current_a"]),
            float(record["reoptimized"]["flattened_optimum_current_a"]),
        }
        for current in sorted(currents):
            cases.extend(
                _case_pair(
                    "PbSe/Cr",
                    "representation_choice",
                    scenario_id,
                    couple,
                    current,
                )
            )

    # The +/-0.03 empirical-profile states used for the central difference.
    flattened = _flatten(base)
    for epsilon in (-0.03, 0.03):
        cases.append(
            Case(
                "PbSe/Cr",
                "adjoint_finite_difference",
                f"empirical_common_mode_epsilon_{epsilon:+.2f}",
                "perturbed",
                nominal_current,
                build_empirical_perturbed_couple(flattened, base, epsilon=epsilon),
            )
        )
    return cases


def _bts_perturbed(
    couple: TemperatureDependentNumericalCouple,
    epsilon: float,
) -> TemperatureDependentNumericalCouple:
    mode, derivative, _ = bts.endpoint_zero_mode(
        couple.cold_temperature_k, couple.hot_temperature_k
    )
    return bts.build_couple(
        (couple.p_leg, couple.n_leg),
        couple.cold_temperature_k,
        couple.hot_temperature_k,
        epsilon=epsilon,
        mode=mode,
        mode_derivative=derivative,
    )


def build_bts_cases() -> list[Case]:
    transport, _ = bts.validate_sources_and_load_transport()
    nominal_legs = bts.build_legs(transport)
    result = json.loads(BTS_JSON.read_text(encoding="utf-8"))
    cases: list[Case] = []

    def add_triplet(
        family: str,
        scenario: str,
        couple: TemperatureDependentNumericalCouple,
        current: float,
    ) -> None:
        cases.append(Case("BTS/BST", family, scenario, "baseline", current, couple))
        for epsilon in (-bts.CENTRAL_EPSILON, bts.CENTRAL_EPSILON):
            cases.append(
                Case(
                    "BTS/BST",
                    family,
                    scenario,
                    f"endpoint_zero_epsilon_{epsilon:+.3f}",
                    current,
                    _bts_perturbed(couple, epsilon),
                )
            )

    for record in result["current_scan"]:
        current = float(record["current_a"])
        couple = bts.build_couple(
            nominal_legs,
            bts.PRIMARY_COLD_TEMPERATURE_K,
            bts.PRIMARY_HOT_TEMPERATURE_K,
        )
        add_triplet("current_scan", f"nominal_I_{current:.3f}", couple, current)

    for record in result["method_bound_corner_envelope"]["records"]:
        gains = tuple(float(value) for value in record["gains_pS_nS_pSigma_nSigma_pKappa_nKappa"])
        legs = bts.build_legs(transport, gains=gains)
        couple = bts.build_couple(
            legs,
            bts.PRIMARY_COLD_TEMPERATURE_K,
            bts.PRIMARY_HOT_TEMPERATURE_K,
        )
        code = "".join("p" if int(value) > 0 else "m" for value in record["signs_pS_nS_pSigma_nSigma_pKappa_nKappa"])
        add_triplet("six_property_method_corners", f"corner_{code}", couple, bts.PRIMARY_CURRENT_A)

    for index, record in enumerate(result["thermal_contact_and_parasitic_nuisance"]["records"]):
        couple = bts.build_couple(
            nominal_legs,
            float(record["cold_leg_temperature_k"]),
            float(record["hot_leg_temperature_k"]),
        )
        add_triplet(
            "thermal_contact_endpoint_states",
            f"contact_ratio_{float(record['contact_ratio_chi_equal_cold_hot']):.3f}",
            couple,
            bts.PRIMARY_CURRENT_A,
        )
    return cases


def _deduplicate(cases: Iterable[Case]) -> list[Case]:
    # Keep every named scenario, but eliminate exact repeats created when an
    # optimum equals the nominal current to floating-point precision.
    output: list[Case] = []
    seen: set[tuple[str, str, str, str, int]] = set()
    for case in cases:
        key = (
            case.material_family,
            case.scenario_family,
            case.scenario_id,
            case.variant,
            int(round(case.current_a * 1.0e9)),
        )
        if key not in seen:
            seen.add(key)
            output.append(case)
    return output


def run_validation() -> dict[str, Any]:
    cases = _deduplicate([*build_pbse_cases(), *build_bts_cases()])
    records: list[dict[str, Any]] = []
    for index, case in enumerate(cases, start=1):
        point = _solve(case.couple, case.current_a)
        records.append(
            _diagnose_leg(case.couple.p_leg, point.p_leg, case=case, leg_name="p")
        )
        records.append(
            _diagnose_leg(case.couple.n_leg, point.n_leg, case=case, leg_name="n")
        )
        if index % 100 == 0:
            print(f"completed {index}/{len(cases)} couple baselines", flush=True)

    maximum_eta_record = max(records, key=lambda row: row["poincare_eta"])
    maximum_liouville_record = max(
        records, key=lambda row: row["liouville_poincare_eta"]
    )
    minimum_determinant_record = min(
        records, key=lambda row: row["homogeneous_shooting_determinant_absolute"]
    )
    maximum_energy_residual = max(
        abs(float(row["baseline_energy_residual_fraction"])) for row in records
    )
    summary_by_material: dict[str, Any] = {}
    for material in sorted({str(row["material_family"]) for row in records}):
        selected = [row for row in records if row["material_family"] == material]
        worst = max(selected, key=lambda row: row["poincare_eta"])
        worst_liouville = max(
            selected, key=lambda row: row["liouville_poincare_eta"]
        )
        minimum_det = min(
            selected,
            key=lambda row: row["homogeneous_shooting_determinant_absolute"],
        )
        summary_by_material[material] = {
            "couple_baselines": len(selected) // 2,
            "leg_baselines": len(selected),
            "maximum_poincare_eta": float(worst["poincare_eta"]),
            "minimum_coercivity_margin_lower_bound": float(
                1.0 - worst["poincare_eta"]
            ),
            "maximum_liouville_poincare_eta": float(
                worst_liouville["liouville_poincare_eta"]
            ),
            "minimum_liouville_coercivity_margin_lower_bound": float(
                1.0 - worst_liouville["liouville_poincare_eta"]
            ),
            "worst_eta_case": {
                key: worst[key]
                for key in (
                    "scenario_family",
                    "scenario_id",
                    "variant",
                    "current_a",
                    "leg",
                )
            },
            "minimum_absolute_shooting_determinant": float(
                minimum_det["homogeneous_shooting_determinant_absolute"]
            ),
        }

    checks = {
        "all_weighted_poincare_sufficient_conditions_pass": bool(
            maximum_eta_record["poincare_eta"] < 1.0
        ),
        "every_state_has_an_analytic_sufficient_condition": bool(
            all(
                row["at_least_one_analytic_sufficient_condition_passes"]
                for row in records
            )
        ),
        "all_shooting_determinants_nonzero": bool(
            minimum_determinant_record["homogeneous_shooting_determinant_absolute"]
            > 1.0e-6
        ),
        "all_baseline_energy_residuals_pass": bool(maximum_energy_residual < 1.0e-7),
    }
    require(all(checks.values()), f"nondegeneracy validation failed: {checks}")

    inputs = [
        Path(__file__),
        PB_IDENT_JSON,
        PB_COMMON_JSON,
        BTS_JSON,
        ROOT / "scripts/tec_1d_solver/temperature_dependent.py",
        ROOT / "scripts/analysis/analyze_common_mode_transfer_kernel.py",
    ]
    return {
        "schema_version": SCHEMA_VERSION,
        "analysis_id": ANALYSIS_ID,
        "mathematical_statement": {
            "normalized_adjoint": "psi_uu+c1 psi_u+c0 psi=0",
            "coefficients": (
                "c1=I_i tau L/(kappa A), "
                "c0=rho_T I_i^2 L^2/(kappa A^2)"
            ),
            "integrating_factor": "P(u)=exp(integral_0^u c1(s) ds)",
            "self_adjoint_form": "(P psi_u)_u+P c0 psi=0",
            "sufficient_condition": (
                "eta=(Pmax/Pmin)||max(c0,0)||_infinity/pi^2<1"
            ),
            "liouville_form": (
                "psi=exp[-A/2]z, A'=c1; z_uu+V z=0 with "
                "V=c0-c1_u/2-c1^2/4"
            ),
            "sharper_sufficient_condition": (
                "eta_L=||max(V,0)||_infinity/pi^2<1"
            ),
            "scope": (
                "Sufficient, not necessary. The shooting determinant independently "
                "tests the exact one-dimensional homogeneous Dirichlet problem."
            ),
        },
        "coverage": {
            "couple_baselines": len(cases),
            "leg_baselines": len(records),
            "scenario_families": sorted(
                {str(row["scenario_family"]) for row in records}
            ),
            "description": (
                "Complete PbSe signed-current sweep; PbSe structured Seebeck, "
                "monotone knot, representation, and sigma/kappa scenarios at fixed "
                "and reoptimized currents; PbSe adjoint finite-difference states; "
                "BTS/BST current scan, all 64 six-property corners, central finite-"
                "difference states, and thermal-contact endpoint states."
            ),
        },
        "summary": {
            "maximum_poincare_eta": float(maximum_eta_record["poincare_eta"]),
            "minimum_coercivity_margin_lower_bound": float(
                1.0 - maximum_eta_record["poincare_eta"]
            ),
            "maximum_eta_record": maximum_eta_record,
            "maximum_liouville_poincare_eta": float(
                maximum_liouville_record["liouville_poincare_eta"]
            ),
            "minimum_liouville_coercivity_margin_lower_bound": float(
                1.0 - maximum_liouville_record["liouville_poincare_eta"]
            ),
            "maximum_liouville_record": maximum_liouville_record,
            "minimum_absolute_shooting_determinant": float(
                minimum_determinant_record[
                    "homogeneous_shooting_determinant_absolute"
                ]
            ),
            "minimum_determinant_record": minimum_determinant_record,
            "maximum_baseline_energy_residual_fraction": float(
                maximum_energy_residual
            ),
            "by_material": summary_by_material,
        },
        "validation_checks": checks,
        "records": records,
        "input_bindings": {
            locator(path): sha256_file(path) for path in inputs if path.is_file()
        },
        "runtime": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "platform": platform.platform(),
        },
        "scope": {
            "supported_result": (
                "The homogeneous Dirichlet linearized adjoint is nondegenerate "
                "for every one-dimensional state used in the reported PbSe and "
                "BTS/BST calculations; all states satisfy an explicit weighted "
                "Poincare sufficient condition."
            ),
            "limitation": (
                "The sufficient bound proves global well-posedness for arbitrary "
                "currents, arbitrary material functions, or untested device states."
            ),
        },
    }


CSV_FIELDS = (
    "material_family",
    "scenario_family",
    "scenario_id",
    "variant",
    "current_a",
    "leg",
    "signed_branch_current_a",
    "temperature_minimum_k",
    "temperature_maximum_k",
    "c1_minimum",
    "c1_maximum",
    "c0_minimum",
    "c0_maximum",
    "integrating_factor_ratio",
    "positive_c0_supremum",
    "poincare_eta",
    "coercivity_margin_lower_bound",
    "liouville_potential_minimum",
    "liouville_potential_maximum",
    "liouville_poincare_eta",
    "liouville_coercivity_margin_lower_bound",
    "at_least_one_analytic_sufficient_condition_passes",
    "homogeneous_shooting_determinant",
    "homogeneous_shooting_determinant_absolute",
    "baseline_energy_residual_fraction",
)


def write_outputs(result: dict[str, Any], json_path: Path, csv_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    with csv_path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for record in result["records"]:
            writer.writerow({key: record[key] for key in CSV_FIELDS})


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--csv-output", type=Path, default=DEFAULT_CSV)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    result = run_validation()
    write_outputs(result, args.json_output, args.csv_output)
    print(
        json.dumps(
            {
                "couple_baselines": result["coverage"]["couple_baselines"],
                "maximum_eta": result["summary"]["maximum_poincare_eta"],
                "minimum_shooting_determinant": result["summary"][
                    "minimum_absolute_shooting_determinant"
                ],
                "validation_checks": result["validation_checks"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
