"""Transparent reference models and conservative 1D thermoelectric solvers.

The constant-property analytic and finite-difference limits remain independent
verification targets for the temperature-dependent conservative solver.
"""

from .constant_properties import (
    COP,
    I_opt_for_max_Qc,
    Pin,
    Qc,
    Qh,
    V,
    ConstantPropertyCouple,
    OperatingPoint,
    energy_residual,
    evaluate,
)
from .finite_difference import (
    ConstantPropertyLeg,
    ConstantPropertyNumericalCouple,
    LegFieldSolution,
    NumericalOperatingPoint,
    solve_constant_couple,
)
from .temperature_dependent import (
    ConstantTemperatureProperty,
    LinearTemperatureProperty,
    PchipTemperatureProperty,
    PropertyDomainError,
    SolverConvergenceError,
    TemperatureDependentLeg,
    TemperatureDependentLegSolution,
    TemperatureDependentNumericalCouple,
    TemperatureDependentOperatingPoint,
    solve_temperature_dependent_couple,
    solve_temperature_dependent_leg,
)
from .operating_controls import (
    ControlSolveError,
    ControlledOperatingPoint,
    solve_bulk_at_cold_heat_load,
    solve_bulk_at_input_power,
    solve_bulk_at_voltage,
)
from .boundary_network import (
    REJECTION_NUMERICAL_INVALID,
    REJECTION_PROPERTY_DOMAIN,
    SYNTHETIC_DATA_ROLE,
    BoundaryNetworkConvergenceDiagnostics,
    BoundaryNetworkOperatingPoint,
    BoundaryNetworkSolveReport,
    BoundaryNetworkSolverOptions,
    FixedCurrentBoundaryNetwork,
    ReservoirThermalContacts,
    SeriesElectricalContacts,
    TwoReservoirParasitic,
    solve_fixed_current_boundary_network,
)

__all__ = [
    "COP",
    "I_opt_for_max_Qc",
    "Pin",
    "Qc",
    "Qh",
    "V",
    "ConstantPropertyCouple",
    "OperatingPoint",
    "energy_residual",
    "evaluate",
    "ConstantPropertyLeg",
    "ConstantPropertyNumericalCouple",
    "LegFieldSolution",
    "NumericalOperatingPoint",
    "solve_constant_couple",
    "ConstantTemperatureProperty",
    "LinearTemperatureProperty",
    "PchipTemperatureProperty",
    "PropertyDomainError",
    "SolverConvergenceError",
    "TemperatureDependentLeg",
    "TemperatureDependentLegSolution",
    "TemperatureDependentNumericalCouple",
    "TemperatureDependentOperatingPoint",
    "solve_temperature_dependent_couple",
    "solve_temperature_dependent_leg",
    "ControlSolveError",
    "ControlledOperatingPoint",
    "solve_bulk_at_cold_heat_load",
    "solve_bulk_at_input_power",
    "solve_bulk_at_voltage",
    "REJECTION_NUMERICAL_INVALID",
    "REJECTION_PROPERTY_DOMAIN",
    "SYNTHETIC_DATA_ROLE",
    "BoundaryNetworkConvergenceDiagnostics",
    "BoundaryNetworkOperatingPoint",
    "BoundaryNetworkSolveReport",
    "BoundaryNetworkSolverOptions",
    "FixedCurrentBoundaryNetwork",
    "ReservoirThermalContacts",
    "SeriesElectricalContacts",
    "TwoReservoirParasitic",
    "solve_fixed_current_boundary_network",
]
